### ISSUE TITLE
Enable HWC

### ISSUE THREAD

**Issue by ghost** [Exynos7580/android_device_samsung_a3xeltexx#10]
Hi guys, i found the main cause of battery draining when screen is on.
It's due to the HWC, we are always using the GPU to compose the screen by using there's tags : 
```
# HWC
debug.hwc.force_gpu=1
debug.hwc.otf=1
debug.hwc.winupdate=1
```

So the goal is to remove this, and make HWC work (it will compile and boot but screen will have bugs (black status bar, and some other graphical bugs).
GPU uses too much battery and shouldn't be used to compose screen (except on games).

Other thing is surely to use `BOARD_USES_HWC_SERVICES := true` but it generate some compilation errors due to our hardware : 
```
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:42:5: warning: field 'bootFinishedCallback' will be initialized after field 'doPSRExit' [-Wreorder]
    bootFinishedCallback(NULL),
    ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:74:45: warning: unused parameter 'black' [-Wunused-parameter]
void ExynosHWCService::setWFDSleepCtrl(bool black)
                                            ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:212:22: error: use of undeclared identifier 'V4L2_DV_1080I60_SB_HALF'
        resolution = V4L2_DV_1080I60_SB_HALF;
                     ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:217:22: error: use of undeclared identifier 'V4L2_DV_1080I59_94_SB_HALF'
        resolution = V4L2_DV_1080I59_94_SB_HALF;
                     ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:243:53: warning: unused parameter 'channels' [-Wunused-parameter]
void ExynosHWCService::setHdmiAudioChannel(uint32_t channels)
                                                    ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:45: warning: unused parameter 'fd1' [-Wunused-parameter]
int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                            ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:55: warning: unused parameter 'fd2' [-Wunused-parameter]
int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                                      ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:276:80: warning: unused parameter 'wfd_info' [-Wunused-parameter]
int ExynosHWCService::getWFDOutputInfo(int *fd1, int *fd2, struct wfd_layer_t *wfd_info)
                                                                               ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:293:10: error: use of undeclared identifier 'V4L2_DV_480P59_94'
    case V4L2_DV_480P59_94:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:294:10: error: use of undeclared identifier 'V4L2_DV_480P60'
    case V4L2_DV_480P60:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:298:10: error: use of undeclared identifier 'V4L2_DV_576P50'
    case V4L2_DV_576P50:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:302:10: error: use of undeclared identifier 'V4L2_DV_720P24'
    case V4L2_DV_720P24:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:303:10: error: use of undeclared identifier 'V4L2_DV_720P25'
    case V4L2_DV_720P25:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:304:10: error: use of undeclared identifier 'V4L2_DV_720P30'
    case V4L2_DV_720P30:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:305:10: error: use of undeclared identifier 'V4L2_DV_720P50'
    case V4L2_DV_720P50:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:306:10: error: use of undeclared identifier 'V4L2_DV_720P59_94'
    case V4L2_DV_720P59_94:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:307:10: error: use of undeclared identifier 'V4L2_DV_720P60'
    case V4L2_DV_720P60:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:308:10: error: use of undeclared identifier 'V4L2_DV_720P60_FP'
    case V4L2_DV_720P60_FP:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:309:10: error: use of undeclared identifier 'V4L2_DV_720P60_SB_HALF'
    case V4L2_DV_720P60_SB_HALF:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:310:10: error: use of undeclared identifier 'V4L2_DV_720P60_TB'
    case V4L2_DV_720P60_TB:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:311:10: error: use of undeclared identifier 'V4L2_DV_720P59_94_FP'
    case V4L2_DV_720P59_94_FP:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:312:10: error: use of undeclared identifier 'V4L2_DV_720P59_94_SB_HALF'
    case V4L2_DV_720P59_94_SB_HALF:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:313:10: error: use of undeclared identifier 'V4L2_DV_720P59_94_TB'
    case V4L2_DV_720P59_94_TB:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:314:10: error: use of undeclared identifier 'V4L2_DV_720P50_FP'
    case V4L2_DV_720P50_FP:
         ^
hardware/samsung_slsi-cm/exynos5/libhwcService/ExynosHWCService.cpp:315:10: error: use of undeclared identifier 'V4L2_DV_720P50_SB_HALF'
    case V4L2_DV_720P50_SB_HALF:
         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
6 warnings and 20 errors generated.
```

Anyway, i post this if anyone knows a way to fix our HW Composer. (i'm trying too :D)
Good luck!

**Comment by messi2050** [comment]
Hmm.. Not sure about that since s6/note 5 and s7 all have this flag too...

**Comment by ghost** [comment]
k3gxx enabled their HWC successfully and our stock TW rom don't use this flag "force_gpu"
(k3gxx: https://github.com/LineageOS/android_device_samsung_k3gxx/commit/4db455172a2305baad4039f6a7c2275cda9c041d)

**Comment by messi2050** [comment]
You are missing those commits
https://github.com/LineageOS/android_kernel_samsung_exynos7420/commit/95ee30cbb049900f7ccbea044ad44a21387f58fc#diff-433cb8c5000433f36fe655fd19f66189
https://github.com/LineageOS/android_kernel_samsung_exynos7420/commit/e3bae7a81cae779c49399fd0e53278c6d92aac57#diff-433cb8c5000433f36fe655fd19f66189

**Comment by vlourme** [comment]
Nice, i thought it was hardware related, it try when i'll back at office

**Comment by ghost** [comment]
It build now but i'm having a blackscreen after bootlogo. I think it's normal i'm trying to find a fix...

Edit: wait i surely did mistake with gralloc, re-trying :d 
Edit 2: i fixed blackscreen (i wrong implemented gralloc), but now i'm having some issues from HWC (black status bar, black graphical elements), i already had this before using `BOARD_USES_HWC_SERVICES`

**Comment by Sekilsgs2** [comment]
i'm think need recompile all libs that need hwc service.. and try again

**Comment by messi2050** [comment]
Agree a clean build should be good

**Comment by Sekilsgs2** [comment]
i'm recompile with this flag and now have random reboots (when open many windows or keyboard)

**Comment by Sekilsgs2** [comment]
bad idea. hwc need gscaler but our soc don't have this. (and other new Samsung soc )

**Comment by ghost** [comment]
But why does the screen consumes too much battery ?

**Comment by Sekilsgs2** [comment]
Reduse bright, disable livedisplay. And amoled always eat battary more then other process...
For me - battery time good.. But i'm use stock kernel from nogat...

**Comment by ghost** [comment]
there is surely an explanation by a bug, in same conditions the stock rom don't consume much battery :/ Also stock rom don't used "force_gpu" so it means stock rom has a working hwc right?

**Comment by ghost** [comment]
Just saw you fixed the graphical bugs when disabled force_gpu, nice job!
I'll try to fix the random reboot, i'm building with disabled force_gpu and last changes

**Comment by Sekilsgs2** [comment]
yes Samsung use hwc. but we can only wait when developers fix fix oss gralloc.. :)

**Comment by ghost** [comment]
I finished the build and as i can see, it's not a gralloc issue :/
The status bar is well fixed, but i have problem with dialog box and some other graphical things and also i'm getting stuck on dialog box (that need reboot), i used the proprietary gralloc

**Comment by ghost** [comment]
Finally found a fix! https://github.com/Exynos7580/android_device_samsung_exynos7580-common/commit/c1c508e442f97ddd24e9796f7242c73281f4c934
(i found code from 7420 TeamNexus)

**Comment by Sekilsgs2** [comment]
max overlay =1  fix all issues besides random reboots...

**Comment by ghost** [comment]
all is working, only problem is video/media (zerolte have same issue)
edit: all omx is crashed (camera don't work too)
