### ISSUE TITLE
List of bugs

### ISSUE THREAD

**Issue by ghost** [Exynos7580/android_device_samsung_a3xeltexx#12]
_I open a list of bugs to know the work remaining._

- [x] H/W Composer
- [ ] Ambiant display `screen don't woke up after receiving notification`
- [ ] Hardware buttons **back** and **menu/app_switch** isn't working on **A310M** and **A310N0**
- [ ] Bluetooth speaker for calls

_Things that need optimization_

- [ ] Battery life `on RessurectionRemix, our battery life is bad`

_Need tester_

- [ ] FlipFlap support `added at 17-09-2017, now need tester (i don't have flip cover)`
- [x] NFC

I let you discuss of all bugs

**Updates**

- 19/09/2017: 
  - HWC has been tested and working (media, camera and other OMX work is working).
  - Battery is still bad even with HWC enabled
  - NFC seems work

**Comment by sinisa94** [comment]
I would suggest to find out which touch panels are present in models "m" and "n0" of a310, and add their dtb-s.

**Comment by ghost** [comment]
@sinisa94 M and N0 have same kernel so the same DBTS, unfortunately I don't have idea actually, I compared the M touchkey with F touchkey path, and they don't have differences

Edit: i was wrong they have different DTBS, working on it...

**Comment by Sekilsgs2** [comment]
`_Hardware buttons back and menu/app_switch isn't working on A310M and A310N0_`
Maybe kernel generate other values of key events - need try detect - 
https://play.google.com/store/apps/details?id=com.sonelli.keywatcher&hl=ru
and see logs
or try compare source code from 
http://opensource.samsung.com/reception/receptionSub.do?method=sub&sub=F&searchValue=a310m

**Comment by Sekilsgs2** [comment]
`Ambiant display screen don't woke up after receiving notification`
This is because our decond driver cant support ioctl FB_BLANK_VSYNC_SUSPEND.
If you change in hwcomposer this ioctl to FB_BLANK_UNBLANK  - screen wake normal when receive notifications.
Patch for hardware/samsung_slsi-cm/exynos/libhwc/ExynosHWC.cpp - 
```
    case HWC_POWER_MODE_DOZE_SUSPEND:
        // FIXME: As specified in Exynos framebuffer driver, this will return -EINVAL.
//        fb_blank = FB_BLANK_VSYNC_SUSPEND;
        fb_blank = FB_BLANK_UNBLANK;
```

**Comment by Sekilsgs2** [comment]
p2p not working after reboot (working only after first boot when install rom) - i'm did some tets and find that if /data/misc/wifi/wpa_supplicant.conf have p2p_disabled=1 string - then p2p not working.. but if delete this string and restart phone - p2p working good. But wpa_supplicant daemon write to conf p2p_disabled=1 again.. Maybe this related to kernel drivers.... need fix this.,..

**Comment by ghost** [comment]
I found a lot of things not working when we don't use common kernel (nfc, tether, some apps), i'm trying to make a cleaner kernel on Nougat base

**Comment by ch8matt** [comment]
Flip cover doesn't work. magnet sensor seem doesn't work probably. If it can help you : this sensor is located on the left bottom of the phone and it is aproximatly at 1cm of the edge bottom and 0.50cm of the left bottom. I measured it manually from the center of the sensor
hope it can help you. Ask me if you need to test it

**Comment by ghost** [comment]
@McFy49 Which build tested from which member ? (Sekil or Me, which date)

**Comment by ch8matt** [comment]
I have tested on Sekil build 20171003 and your 20170922 and both have issue with flip cover

**Comment by ghost** [comment]
Where can I download sekils build?

**Comment by ch8matt** [comment]
On 4pda
