### ISSUE TITLE
Build error on sekils device tree

### ISSUE THREAD

**Issue by lukassei** [Exynos7580/android_device_samsung_a3xeltexx#16]
Hello,
I am getting build error on brunch "lineage-15.1_sekil". Every time i try to build from this source i get stuck on this error:

> device/samsung/a3xeltexx/audio_a3/ril_interface.c:195: error: undefined reference to 'SetSoundClockMode'

Can anyone help me with this please? 

> [ 75% 5831/7731] target SharedLib: audio.primary...rmediates/LINKED/audio.primary.universal7580.so)
FAILED: /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/audio.primary.universal7580_intermediates/LINKED/audio.primary.universal7580.so 
/bin/bash -c "/usr/bin/ccache prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ -nostdlib -Wl,-soname,audio.primary.universal7580.so -Wl,--gc-sections -shared /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/crtbegin_so.o /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/audio.primary.universal7580_intermediates/audio_hw.o /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/audio.primary.universal7580_intermediates/ril_interface.o -Wl,--whole-archive  -Wl,--no-whole-archive   /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libunwind_llvm_intermediates/libunwind_llvm.a  /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a   /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,--no-undefined-version -Wl,--no-fix-cortex-a8   -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,--exclude-libs,libunwind_llvm.a -Wl,--no-undefined /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/liblog.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libcutils.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libtinyalsa.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libaudioutils.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libaudioroute.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libsecril-client.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libc++.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libc.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libm.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libdl.so -o /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/audio.primary.universal7580_intermediates/LINKED/audio.primary.universal7580.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/crtend_so.o"
device/samsung/a3xeltexx/audio_a3/ril_interface.c:195: error: undefined reference to 'SetSoundClockMode'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)
[ 75% 5836/7731] target SharedLib: libpac (/home...LIBRARIES/libpac_intermediates/LINKED/libpac.so)
ninja: build stopped: subcommand failed.
13:50:55 ninja failed with: exit status 1

**Comment by Sekilsgs2** [comment]
Yes - need other libsecril-client in hardware_samsung repo - now fixed.. 
update your repo with new local_manifests - i'm update hardware_samsung with my brunch

**Comment by lukassei** [comment]
Okay i am gonna try it now will let you know. 

And what is the state of your device tree at the moment? (Current bugs) 

thanks in advance

**Comment by lukassei** [comment]
unfortunetly there is another undefined refference error.

[ 97% 74359/75995] target SharedLib: libstagefr...ghthw_intermediates/LINKED/libstagefrighthw.so)
FAILED: /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/libstagefrighthw_intermediates/LINKED/libstagefrighthw.so 
/bin/bash -c "/usr/bin/ccache prebuilts/clang/host/linux-x86/clang-4053586/bin/clang++ -nostdlib -Wl,-soname,libstagefrighthw.so -Wl,--gc-sections -shared /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/crtbegin_so.o /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/libstagefrighthw_intermediates/Exynos_OMX_Plugin.o -Wl,--whole-archive  -Wl,--no-whole-archive   /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libunwind_llvm_intermediates/libunwind_llvm.a  /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a   /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libatomic_intermediates/libatomic.a /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/STATIC_LIBRARIES/libgcc_intermediates/libgcc.a -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--icf=safe -Wl,--hash-style=gnu -Wl,--no-undefined-version -Wl,--no-fix-cortex-a8   -target arm-linux-androideabi -Bprebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/arm-linux-androideabi/bin -Wl,--exclude-libs,libunwind_llvm.a -Wl,--no-undefined /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libbinder.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libutils.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libcutils.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libui.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libstagefright_foundation.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libc++.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libc.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libm.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/libdl.so -o /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/SHARED_LIBRARIES/libstagefrighthw_intermediates/LINKED/libstagefrighthw.so /home/jarjarguy_frosty/android/lineage/out/target/product/a3xeltexx/obj/lib/crtend_so.o"
hardware/samsung_slsi-cm/exynos/libstagefrighthw/Exynos_OMX_Plugin.cpp:0: error: undefined reference to '__android_log_assert'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Sekilsgs2** [comment]
:-D
i'm dont remember about this

in 
hardware/samsung_slsi-cm/exynos/libstagefrighthw/Android.mk


```
remove       libstagefright_foundation
add             libstagefright_foundation \
add             liblog
```

i'm don't understand why lineage repo don't have this now...
